### ISSUE TITLE
Doesn't work in nginx 1.9.2 and ipset 6.11

### ISSUE THREAD

**Issue by Anton-Kartashev** [Vasfed/nginx_ipset_blacklist#2] opened 2015-07-07 06:41 UTC
Hello

I have complied module into nginx and add to nginx.conf -

user  root;
http {
...
    blacklist "blacklist";
...
}

and nginx test failed with - 

nginx: [emerg] cannot get ipset "blacklist" from kernel, check nginx to be running as root (ipset kernel module protocol version mismatch) in /etc/nginx/nginx.conf:17

ipset output -

ipset list blacklist |head -n 5
Name: blacklist
Type: hash:ip
Header: family inet hashsize 131072 maxelem 1048576
Size in memory: 3944600
References: 0

OS: Centos 6.6 x64. 

How to resolve this problem?

**Comment by Vasfed** [comment] 2016-06-23 14:59
Current version is incompatible with ipset 6.

Closing as duplicate of #4

**Closed as completed by Vasfed** 2016-06-23 14:59 UTC

**Comment by Anton-Kartashev** [comment] 2016-06-23 15:48
Не прошло и года, спасибо, что хоть ответили.
